apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldap-tls
spec:
  dnsNames:
    - "ldap.${DOMAIN}"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ${DOMAIN}-letsencrypt-issuer
  secretName: ldap-tls
