debug: false
hostname: srv.${DOMAIN}
ingress:
  enabled: true
  includeDefaultExtraAnnotations: true
  ingressClassName: nginx
  extraAnnotations:
    helm.sh/resource-policy: keep
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "${DOMAIN}-letsencrypt-issuer"
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,192.168.100.20"
  tls:
    # options: rancher, letsEncrypt, secret
    source: secret
    secretName: rancher-tls

replicas: 1
tls: ingress

fleet:
  controller:
    replicas: 0
  gitjob:
    replicas: 0
  helmops:
    enabled: true
    replicas: 0
  agent:
    replicas: 0
