apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-pages-tls
spec:
  dnsNames:
    - pages.${DOMAIN}
    - "*.pages.${DOMAIN}"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ${DOMAIN}-letsencrypt-issuer
  secretName: gitlab-pages-tls
