apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-wildcard-tls
spec:
  dnsNames:
    - git.${DOMAIN}
    - "*.git.${DOMAIN}"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ${DOMAIN}-letsencrypt-issuer
  secretName: gitlab-wildcard-tls
